oligo_profil/urls.py
import django_cas_ng.views
from django.conf.urls import url
from .views import index, edit_profile

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^edit-profile/', edit_profile, name='edit-profile'),
	
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import oligo_login.urls as oligo_login
import oligo_profil.urls as oligo_profil
import oligo_status.urls as oligo_status
import oligo_riwayat.urls as oligo_riwayat
import oligo_friends.urls as oligo_friends
import django_cas_ng.views


urlpatterns = [

    url(r'^logout/$', django_cas_ng.views.logout, name='cas_ng_logout'),
    url(r'^callback/$', django_cas_ng.views.callback, name='cas_ng_proxy_callback'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('oligo_login.urls', namespace='oligo_login')),
    url(r'^profil/', include(oligo_profil, namespace='profil')),
    url(r'^login/', include(oligo_login, namespace='login')),
    url(r'^status/', include(oligo_status, namespace='status')),
    url(r'^riwayat/', include(oligo_riwayat, namespace='riwayat')),
    url(r'^friends/', include(oligo_friends, namespace='friends')),

    #url(r'^login/$', include(login,namespace='login')),
]

oligo_profil/models.py
from django.db import models

# Create your models here.
class UserData(models.Model):
    kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True, default='Kosong')
    firstName = models.CharField('Nama Depan', max_length=225)
    lastName = models.CharField('Nama Belakang', max_length=225)
    imageUrl = models.URLField('Foto', default="https://thumbs.dreamstime.com/t/default-male-avatar-profile-picture-icon-grey-man-photo-placeholder-vector-illustration-88414414.jpg")
    email = models.EmailField('Email', default='Kosong')
    profileUrl = models.URLField('Profile LinkedIn', default='Kosong')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

oligo_profil/views.py
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django_cas_ng import utils
from django.views.decorators.csrf import csrf_exempt
from oligo_status.models import StatusKu, User
# from oligo_login.models import User
from oligo_status.views import *

# Create your views here.
response = {}
def index(request):
	if get_data_user(request, 'user_login'):

		set_data_for_session(request)
		kode_identitas = get_data_user(request, 'kode_identitas')
		# pengguna = 0
		# #pengguna = User.objects.get(kode_identitas = kode_identitas)
		# try:
		# 	pengguna = User.objects.get(kode_identitas = kode_identitas)
		# except Exception as e:
		# 	pengguna = create_new_user(request)

		
		response['name'] = request.session['user_login']
		response['role'] = request.session['role']
		response['npm'] = request.session['kode_identitas']
		response['email'] = 'Kosong'
		response['linkin_profile'] = 'Kosong'
		# banyakstat = StatusKu.objects.filter(pengguna = pengguna).all().count()
		# response['jumlah'] = banyakstat

		# if banyakstat > 0:
		# 	response['status_akhir'] = StatusKu.objects.last().description
		# else:
		# 	response['status_akhir'] = "Tidak ada status terbaru"


		html = 'oligo_profil/profil.html'
		return render(request, html, response)
	else:
		response['login'] = False
		html = 'login/login.html'
		return render(request, html, response)

def edit_profile(request):
	print ("#==> masuk dashboard")
	if not get_data_user(request, 'user_login'):
		return HttpResponseRedirect(reverse('oligo_login:index'))
	else:
		response['name'] = request.session['user_login']
		response['role'] = request.session['role']
		response['npm'] = request.session['kode_identitas']
		response['email'] = 'Kosong'
		response['linkin_profile'] = 'Kosong'
		html = 'oligo_profil/edit_profile.html'
		return render(request, html, response)

@csrf_exempt
def save_to_database(request):
	if(request.method == 'POST'):
		firstName = request.POST['firstName']
		lastName = request.POST['lastName']
		imageUrl = request.POST['imageUrl']
		email = request.POST['email']
		profileUrl = request.POST['profileUrl']
		kode_identitas = request.session['kode_identitas']
		exist = User.objects.filter(kode_identitas=kode_identitas).exists()
		if(not exist):
			user = User(firstName=firstName, lastName=lastName, imageUrl=imageUrl, email=email, profileUrl=profileUrl, kode_identitas=kode_identitas)
			user.save()
		return JsonResponse({'save':'ok'})

def model_to_dict(obj):
	data = serializers.serialize('json', [obj,])
	struct = json.loads(data)
	data = json.dumps(struct[0]["fields"])
	return data

oligo_profil/templates/oligo_profil/edit_profile.html
{% extends "oligo_profil/layout/base_edit.html" %}
  <script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key: 81kh8t1i9w9aq1
    authorize: true
    onLoad: onLinkedInLoad

</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript">
    // Setup an event listener to make an API call once auth is complete
    function onLinkedInLoad() {
        IN.Event.on(IN, "auth", getProfileData);
    }

    function displayAdmin(data){
      console.log(data)


    }
    // Use the API call wrapper to request the member's profile data
    function getProfileData() {
    IN.API.Profile("me").fields("id", "first-name", "last-name", "headline", "location", "picture-url", "public-profile-url", "email-address").result(displayProfileData).error(onError);
    }
    //Handle the successful return from the API call
    function displayProfileData(data){
        console.log(data.values[0]);
        var obj = JSON.stringify(data.values[0])
        sessionStorage.setItem("data", obj);

        $('.profile-picture').html(
         '<img class="cover" src="'+ data.values[0].pictureUrl + '"/>'
        );

        var user = data.values[0];
        document.getElementById("name").innerHTML = user.firstName+' '+user.lastName;
        document.getElementById("email").innerHTML = user.emailAddress;
        document.getElementById("link").innerHTML = user.publicProfileUrl;

    }
    // Handle an error response from the API call
    function onError(error) {
        console.log(error);
    }
    // Destroy the session of linkedin
    function logout(){
        IN.User.logout(removeProfileData);
    }
    // Remove profile data from page
    function removeProfileData(){
        document.getElementById('profileData').remove();
    }
    function saveLinkedIn(){
      console.log("success");
      var data = sessionStorage.getItem("data");
      var obj = JSON.parse(data);
      insertDatabase(obj.firstName,obj.lastName,obj.pictureUrl,obj.emailAddress,obj.publicProfileUrl);
    }

    var insertDatabase = function(firstName,lastName,imageUrl,email,profileUrl) {
        $.ajax({
            method: "POST",
            url: 'http://oligo271.herokuapp.com/profil/save_to_database/',
            data: {
              firstName: firstName,
              lastName: lastName,
              imageUrl: imageUrl,
              email: email,
              profileUrl: profileUrl
            },
            success : function (user) {
                console.log(user);
            },
            error : function (error) {
                console.log(error);
            }
        });
    };
</script>

{% block content %}

<div class="container" align="center">
	<div class = "col-xs-6">
	   <br>
	   <img style="height:100px;width=100px;border-radius:50%;" class="picture" src="https://thumbs.dreamstime.com/t/default-male-avatar-profile-picture-icon-grey-man-photo-placeholder-vector-illustration-88414414.jpg">
        <p>NPM {{ npm }}</p>
	   </div>
        <div class="col-xs-3">
            <br><br><br><br>
            <div class="col-xs-6">
				<a class="btn btn-primary"> Simpan </a>
            </div>
			<div class="col-xs-6">
				<a class="btn btn-primary" href="{% url 'profil:index' %}"> Keluar </a>
            </div>

    </div>
</div>
<script type="in/Login"></script>
  <div id="profileData" style=" font-size: 15px;">
      <p><a href="javascript:void(0);" onclick="logout()">Logout</a></p>
      <div id="picture"></div>
      <div class="info">
        <h5 style=" font-size: 20px;"> Data Pribadi </h5>
        <p id="name"></p>
        <p id="email"></p>
        <p id="link"></p>
      </div>
  </div><br>

<br><br>
<div class="container">
    <div class = "col-xs-6">
        <p> Keahlian </p>
        <div class = "col-xs-2"> 1. </div>
        <div class = "col-xs-4">
            <select name="ability">
                <option value="java">Java</option>
                <option value="c#">C#</option>
                <option value="python">Python</option>
                <option value="erlang">Erlang</option>
                <option value="kotlin">Kotlin</option>
            </select>
        </div>
        <div class = "col-xs-2"> Level </div>
        <div class = "col-xs-4">
            <select name="level">
                <option value="beginner">Beginner</option>
                <option value="intermediate">Intermediate</option>
                <option value="advanced">Advanced</option>
                <option value="expert">Expert</option>
                <option value="legend">Legend</option>
            </select>
        </div>
    </div>
    <div class = "col-xs-2">
        <p>Tampilkan Nilai</p>
        <form action="">
            <input type="radio" name="score_visibility" value="tidak"> Tidak <br>
            <input type="radio" name="score_visibility" value="ya"> Ya <br>
        </form>
    </div>
</div>
<br><br>
<div class="container">
	<a class="btn btn-primary"> Tambahkan Keahlian </a>
</div>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

{% endblock %}

oligo_profil/templates/oligo_profil/profil.html
{% extends "oligo_profil/layout/base.html" %}
{% block content %}
<div class="panel panel-info">
    <div class="panel-heading">
        <h2> Profil {{ name }} </h2>
    </div>
    <div class="panel-body">
        <p>Nama : {{ name }}</p>
		<p>NPM : {{ npm }}</p>
		<p>Keahlian : {{ role }}</p>
		<p>Email : {{ email }}</p>
		<p>Profile LinkedIn : {{ linkin_profile }}</p>
    </div>
</div>
{% endblock %}