oligo_profil/urls.py
import django_cas_ng.views
from django.conf.urls import url
from .views import index, edit_profile

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^edit-profile/', edit_profile, name='edit-profile'),
	
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import oligo_login.urls as oligo_login
import oligo_profil.urls as oligo_profil
import oligo_status.urls as oligo_status
import oligo_riwayat.urls as oligo_riwayat
import oligo_friends.urls as oligo_friends
import django_cas_ng.views


urlpatterns = [

    url(r'^logout/$', django_cas_ng.views.logout, name='cas_ng_logout'),
    url(r'^callback/$', django_cas_ng.views.callback, name='cas_ng_proxy_callback'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('oligo_login.urls', namespace='oligo_login')),
    url(r'^profil/', include(oligo_profil, namespace='profil')),
    url(r'^login/', include(oligo_login, namespace='login')),
    url(r'^status/', include(oligo_status, namespace='status')),
    url(r'^riwayat/', include(oligo_riwayat, namespace='riwayat')),
    url(r'^friends/', include(oligo_friends, namespace='friends')),

    #url(r'^login/$', include(login,namespace='login')),
]

oligo_profil/models.py
from django.db import models

# Create your models here.
class UserData(models.Model):
    kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True, default='Kosong')
    firstName = models.CharField('Nama Depan', max_length=225)
    lastName = models.CharField('Nama Belakang', max_length=225)
    imageUrl = models.URLField('Foto', default="https://thumbs.dreamstime.com/t/default-male-avatar-profile-picture-icon-grey-man-photo-placeholder-vector-illustration-88414414.jpg")
    email = models.EmailField('Email', default='Kosong')
    profileUrl = models.URLField('Profile LinkedIn', default='Kosong')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

oligo_profil/views.py
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django_cas_ng import utils
from django.views.decorators.csrf import csrf_exempt
from oligo_status.models import StatusKu, User
# from oligo_login.models import User
from oligo_status.views import *

# Create your views here.
response = {}
def index(request):
	if get_data_user(request, 'user_login'):

		set_data_for_session(request)
		kode_identitas = get_data_user(request, 'kode_identitas')
		# pengguna = 0
		# #pengguna = User.objects.get(kode_identitas = kode_identitas)
		# try:
		# 	pengguna = User.objects.get(kode_identitas = kode_identitas)
		# except Exception as e:
		# 	pengguna = create_new_user(request)

		
		response['name'] = request.session['user_login']
		response['role'] = request.session['role']
		response['npm'] = request.session['kode_identitas']
		response['email'] = 'Kosong'
		response['linkin_profile'] = 'Kosong'
		# banyakstat = StatusKu.objects.filter(pengguna = pengguna).all().count()
		# response['jumlah'] = banyakstat

		# if banyakstat > 0:
		# 	response['status_akhir'] = StatusKu.objects.last().description
		# else:
		# 	response['status_akhir'] = "Tidak ada status terbaru"


		html = 'oligo_profil/profil.html'
		return render(request, html, response)
	else:
		response['login'] = False
		html = 'login/login.html'
		return render(request, html, response)

def edit_profile(request):
	print ("#==> masuk dashboard")
	if not get_data_user(request, 'user_login'):
		return HttpResponseRedirect(reverse('oligo_login:index'))
	else:
		response['name'] = request.session['user_login']
		response['role'] = request.session['role']
		response['npm'] = request.session['kode_identitas']
		response['email'] = 'Kosong'
		response['linkin_profile'] = 'Kosong'
		html = 'oligo_profil/edit_profile.html'
		return render(request, html, response)

@csrf_exempt
def save_to_database(request):
	if(request.method == 'POST'):
		firstName = request.POST['firstName']
		lastName = request.POST['lastName']
		imageUrl = request.POST['imageUrl']
		email = request.POST['email']
		profileUrl = request.POST['profileUrl']
		kode_identitas = request.session['kode_identitas']
		exist = User.objects.filter(kode_identitas=kode_identitas).exists()
		if(not exist):
			user = User(firstName=firstName, lastName=lastName, imageUrl=imageUrl, email=email, profileUrl=profileUrl, kode_identitas=kode_identitas)
			user.save()
		return JsonResponse({'save':'ok'})

def model_to_dict(obj):
	data = serializers.serialize('json', [obj,])
	struct = json.loads(data)
	data = json.dumps(struct[0]["fields"])
	return data

oligo_profil/templates/oligo_profil/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    

    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <title>
        {% block title %} Oligo {% endblock %}
    </title>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand">OLIGO</a>
            </div>
            <ul class="nav navbar-nav">
              <li class="active"><a href="/profil">Profil</a></li>
              <li><a href="/riwayat">Riwayat</a></li>
              <li><a href="{% url 'status:index' %}">Status</a></li>
              <li><a href="/friends">Teman</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              
              <li><a href="/logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
            </ul>
        </div>
    </nav> 
    <div class="panel panel-default">
    <div class="panel panel-heading">Welcome {{ name }}</div>
       <div class = "col-xs-2">
       <br>
       <img style="height:100px;width=100px;border-radius:50%;" class="picture" src="https://thumbs.dreamstime.com/t/default-male-avatar-profile-picture-icon-grey-man-photo-placeholder-vector-illustration-88414414.jpg">
       </div>
        <div class="col-xs-3">
            <br>
            
            <div class="rows">
                <a class="btn btn-primary"> Lihat Forum </a>
            </div>
            <br>
            <div class="rows">
                <a class="btn btn-primary" href="{% url 'profil:edit-profile' %}"> Edit Profile </a>
            </div>
        
        </div>
        <div class="col-xs-7">
            <h3>Jumlah Status : {{ jumlah }}</h3>
            <h3>Latest Post</h3>
            <p>" {{ status_akhir }} "</p>
            <br>
            <br>
        </div>
    
  
</div>
</body>
<header>
    
    <!-- Your Header Here -->
</header>
<content>
    
        

        {% block content %}
        <!-- Your Content Here -->
        {% endblock %}
    </div>
</content>
<footer>
    <hr>
    {% block footer %}

    
    <!-- Your Footer Here -->
    {% endblock %}
</footer>

<!-- Jquery n Bootstrap Script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
</body>
</html>

oligo_profil/templates/oligo_profil/layout/base_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">

    <title>
        {% block title %} Oligo {% endblock %}
    </title>
</head>

<header>

    <!-- Your Header Here -->
</header>
<content>



        {% block content %}
        <!-- Your Content Here -->
        {% endblock %}
    </div>
</content>
<footer>
    <hr>
    {% block footer %}


    <!-- Your Footer Here -->
    {% endblock %}
</footer>

<!-- Jquery n Bootstrap Script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>