oligo_login/urls.py
from django.conf.urls import url
from .views import *

# /sol
from .custom_auth import auth_login, auth_logout

urlpatterns = [

	url(r'^$', index, name='index'),


    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout')
    ]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import oligo_login.urls as oligo_login
import oligo_profil.urls as oligo_profil
import oligo_status.urls as oligo_status
import oligo_riwayat.urls as oligo_riwayat
import oligo_friends.urls as oligo_friends
import django_cas_ng.views


urlpatterns = [

    url(r'^logout/$', django_cas_ng.views.logout, name='cas_ng_logout'),
    url(r'^callback/$', django_cas_ng.views.callback, name='cas_ng_proxy_callback'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('oligo_login.urls', namespace='oligo_login')),
    url(r'^profil/', include(oligo_profil, namespace='profil')),
    url(r'^login/', include(oligo_login, namespace='login')),
    url(r'^status/', include(oligo_status, namespace='status')),
    url(r'^riwayat/', include(oligo_riwayat, namespace='riwayat')),
    url(r'^friends/', include(oligo_friends, namespace='friends')),

    #url(r'^login/$', include(login,namespace='login')),
]

oligo_login/models.py
from django.db import models

# Create your models here.
class User(models.Model):
	nama = models.CharField('Nama', max_length=200)
	kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True,)
	role = models.CharField('Role', max_length=100)

oligo_login/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import json
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from .models import User


# Create your views here.
response = {}
def index(request):
	print ("#==> masuk index")
	if 'user_login' in request.session:

		return HttpResponseRedirect(reverse('profil:index'))
	else:
		response['login'] = False;
		html = 'login/login.html'
		return render(request, html, response)

oligo_login/templates/login/login.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Login Mahasiswa</title>
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">


  
</head>

<body>
  <style>
    @import url(https://fonts.googleapis.com/css?family=Tenor+Sans);
html {
  background-color: #5D92BA;
  font-family: "Tenor Sans", sans-serif;
}

.container {
  width: 500px;
  height: 400px;
  margin: 0 auto;
}

.login {
  margin-top: 50px;
  width: 450px;
}

.login-heading {
  font: 1.8em/48px "Tenor Sans", sans-serif;
  color: white;
}

.input-txt {
  width: 100%;
  padding: 20px 10px;
  background: #5D92BA;
  border: none;
  font-size: 1em;
  color: white;
  border-bottom: 1px dotted rgba(250, 250, 250, 0.4);
  box-sizing: border-box;
  transition: background-color 0.5s ease-in-out;
}

.input-txt:-moz-placeholder {
  color: #81aac9;
}

.input-txt:-ms-input-placeholder {
  color: #81aac9;
}

.input-txt::-webkit-input-placeholder {
  color: #81aac9;
}

.input-txt:focus {
  background-color: #4478a0;
}

.login-footer {
  margin: 10px 0;
  overlow: hidden;
  float: left;
  width: 100%;
}

.btn {
  padding: 15px 30px;
  border: none;
  background: white;
  color: #5D92BA;
}

.btn--right {
  float: right;
}

.icon {
  display: inline-block;
}

.icon--min {
  font-size: .9em;
}

.lnk {
  font-size: .8em;
  line-height: 3em;
  color: white;
  text-decoration: none;
}

  </style>
  <div class="container">
  <div class="login">
  	<h1 class="login-heading">
      <strong>Welcome.</strong> Please login.</h1>
      <form method="post" action="{% url 'login:auth_login' %}">
        {% csrf_token %}
        <input type="text" id="username" name="username" placeholder="Username" required="required" class="input-txt">
        <input type="password" id="password" name="password" placeholder="Password" required="required" class="input-txt">
          
          <div class="login-footer">
             <a href="#" class="lnk">
              <span class="icon icon--min">ಠ╭╮ಠ</span> 
              Made By Kelompok 5 Kelas E
            </a>
            <button type="submit" class="btn btn--right">Sign in  </button>
    
          </div>
        
      </form>
  </div>
</div>
  
    <script  src="static/js/index.js"></script>

</body>
</html>